### PR TITLE
Add related articles

### PR DESCRIPTION
**Pull request by nlisgo**
Please offer any feedback.

### CODE REVIEW

**Comment by jhroot** [comment]
related_articles = article.**getattr**('related_article')
can be just
related_articles = article.related_article 
I think. I have only been using **getattr** when I need to pass parameters, but I see Graham has been using it for other calls too, I've asked him if theres a side effect I'm unaware of.

I might have combined the creation, assignment and append of this:
data = {}
           data['type'] = related_article['related_article_type']
           data['href'] = related_article['xlink_href']
           relateds.append(data)

such as:
data = {'type': related_article['related_article_type'], 'href': related_article['xlink_href']}
but thats just a style thing and arguably yours is easier to read

I'd certainly be happy merging this

**Comment by nlisgo** [comment]
Thanks for the feedback. I've made some of the requested changes.

**Comment by jhroot** [comment]
this is fine but needs to be against exp

**Comment by nlisgo** [comment]
There is no exp branch and as these changes do not require changes to elife-tools it might be ok to merge with master?

**Comment by gnott** [comment]
Yes master is the only branch in this repo

**Pull request merged**
